package handler

import (
	"fmt"
	"net/http"
	"net/url"
	"strconv"
	"strings"
	"time"

	"github.com/gin-gonic/gin"
	"github.com/troublesis/rent/internal/model"
	"github.com/troublesis/rent/internal/repository"
	"github.com/troublesis/rent/internal/service"
)

type AdminPaymentHandler struct {
	renderer       Renderer
	paymentService *service.PaymentService
	tenantService  *service.TenantService
}

// paymentRow is a flat, pre-formatted view of one payment record for use in
// the server-side admin templates. Keeping the labels here means the template
// stays a pure projection and we get to share the formatting logic with the
// JSON API.
type paymentRow struct {
	ID                uint
	TenantID          uint
	TenantName        string
	RoomNo            string
	RoomTitle         string
	TenantStatus      string
	TenantStatusLabel string
	Type              string
	TypeLabel         string
	AmountText        string
	AmountFen         int
	PayDate           time.Time
	PayDateLabel      string
	NextDueLabel      string
	Paid              bool
	StatusLabel       string
	Excluded          bool
	ExclusionNote     string
	AutoGenerated     bool
	Overdue           bool
	OverdueDays       int
	OverdueLabel      string
	Note              string
	RentTypeLabel     string
}

// filterChip is the same render-shape used by rooms/tenants for status pills.
type filterChip struct {
	Label  string
	URL    string
	Active bool
}

// sortHeader powers a clickable column header — same idiom as rooms/tenants.
type sortHeader struct {
	Key       string
	Label     string
	URL       string
	Active    bool
	Indicator string
}

type paymentAPIResponse struct {
	Data    []paymentAPIItem  `json:"data"`
	Summary paymentAPISummary `json:"summary"`
	Page    int               `json:"page"`
	Limit   int               `json:"limit"`
	Total   int64             `json:"total"`
	HasMore bool              `json:"has_more"`
}

type paymentAPISummary struct {
	TotalUnpaidAmountFen  int    `json:"total_unpaid_amount_fen"`
	TotalUnpaidAmountText string `json:"total_unpaid_amount_text"`
	TotalPaidAmountFen    int    `json:"total_paid_amount_fen"`
	TotalPaidAmountText   string `json:"total_paid_amount_text"`
	CheckoutPendingCount  int64  `json:"checkout_pending_count"`
	ExcludedCount         int64  `json:"excluded_count"`
}

type paymentExclusionRequest struct {
	Excluded      bool   `json:"excluded"`
	ExclusionNote string `json:"exclusion_note"`
	Note          string `json:"note"`
}

type paymentAPIItem struct {
	ID                uint   `json:"id"`
	PaymentID         uint   `json:"payment_id"`
	TenantID          uint   `json:"tenant_id"`
	TenantName        string `json:"tenant_name"`
	RoomNo            string `json:"room_no"`
	Room              string `json:"room"`
	TenantStatus      string `json:"tenant_status"`
	Phone             string `json:"phone"`
	RentPriceFen      int    `json:"rent_price_fen"`
	RentPriceText     string `json:"rent_price_text"`
	RentType          string `json:"rent_type"`
	RentTypeLabel     string `json:"rent_type_label"`
	PaymentTerms      string `json:"payment_terms"`
	PaymentTermsLabel string `json:"payment_terms_label"`
	CheckinDate       string `json:"checkin_date"`
	LeaseEndDate      string `json:"lease_end_date"`
	PayDate           string `json:"pay_date"`
	NextPayDateLabel  string `json:"next_pay_date_label"`
	Type              string `json:"type"`
	TypeLabel         string `json:"type_label"`
	AmountFen         int    `json:"amount_fen"`
	AmountText        string `json:"amount_text"`
	Paid              bool   `json:"paid"`
	PaymentStatus     string `json:"payment_status"`
	StatusLabel       string `json:"status_label"`
	Excluded          bool   `json:"excluded"`
	ExclusionNote     string `json:"exclusion_note"`
	AutoGenerated     bool   `json:"auto_generated"`
	Overdue           bool   `json:"overdue"`
	OverdueDays       int    `json:"overdue_days"`
	OverdueLabel      string `json:"overdue_label"`
	Note              string `json:"note"`
}

func NewAdminPaymentHandler(renderer Renderer, paymentService *service.PaymentService, tenantService *service.TenantService) *AdminPaymentHandler {
	return &AdminPaymentHandler{renderer: renderer, paymentService: paymentService, tenantService: tenantService}
}

const (
	adminPaymentViewList = "list"
	adminPaymentViewGrid = "grid"
	adminPaymentViewCard = "card"
)

func adminPaymentViewFromQuery(c *gin.Context) string {
	switch c.Query("view") {
	case adminPaymentViewGrid:
		return adminPaymentViewGrid
	case adminPaymentViewCard:
		return adminPaymentViewCard
	default:
		return adminPaymentViewList
	}
}

func paymentListURL(c *gin.Context, overrides map[string]string) string {
	values := url.Values{}
	for key, vals := range c.Request.URL.Query() {
		for _, value := range vals {
			values.Add(key, value)
		}
	}
	for key, value := range overrides {
		if value == "" {
			values.Del(key)
			continue
		}
		values.Set(key, value)
	}
	encoded := values.Encode()
	if encoded == "" {
		return "/admin/payments"
	}
	return "/admin/payments?" + encoded
}

func paymentClearURL(viewMode string) string {
	if viewMode == "" {
		return "/admin/payments"
	}
	return "/admin/payments?view=" + url.QueryEscape(viewMode)
}

func paymentSortValue(filter repository.PaymentFilter) string {
	sortBy := filter.SortBy
	if sortBy == "" {
		sortBy = "next_pay_date"
	}
	sortDir := filter.SortDir
	if sortDir == "" {
		sortDir = "asc"
	}
	return sortBy + ":" + sortDir
}

func paymentRedirectTarget(c *gin.Context) string {
	target := c.PostForm("return_to")
	if strings.HasPrefix(target, "/admin/payments") {
		return target
	}
	return "/admin/payments"
}

func (h *AdminPaymentHandler) List(c *gin.Context) {
	data, err := h.buildPaymentListData(c)
	if err != nil {
		c.String(http.StatusInternalServerError, err.Error())
		return
	}
	if isHTMXRequest(c) {
		h.renderer.RenderPartial(c, http.StatusOK, "admin/payments.html", "admin_payment_list", data)
		return
	}
	h.renderer.Render(c, http.StatusOK, "admin_base.html", "admin/payments.html", data)
}

func (h *AdminPaymentHandler) buildPaymentListData(c *gin.Context) (gin.H, error) {
	now := time.Now()
	if _, err := h.paymentService.GenerateDueRecordsForActiveTenants(now); err != nil {
		return nil, errPaymentGenerate
	}
	filter := paymentFilterFromQuery(c)
	if filter.Limit <= 0 {
		filter.Limit = 20
	}
	viewMode := adminPaymentViewFromQuery(c)
	result, err := h.paymentService.ListPaymentsPage(filter, now)
	if err != nil {
		return nil, errPaymentList
	}
	summary, err := h.paymentService.SummarizePayments(filter, now)
	if err != nil {
		return nil, errPaymentSummary
	}
	tenants, err := h.tenantService.ListTenants(repository.TenantFilter{Status: model.TenantStatusActive})
	if err != nil {
		return nil, errPaymentTenants
	}
	rows := make([]paymentRow, len(result.Payments))
	for i, payment := range result.Payments {
		rows[i] = paymentToRow(payment, now)
	}
	page := normalizePaymentPage(filter.Page)
	limit := normalizePaymentLimit(filter.Limit)
	hasMore := int64(page*limit) < result.Total
	nextPageURL := ""
	if hasMore {
		nextPageURL = paymentListURL(c, map[string]string{"page": strconv.Itoa(page + 1)})
	}
	return gin.H{
		"Title":              "收款记录",
		"Rows":               rows,
		"Summary":            paymentSummaryToAPI(summary),
		"Tenants":            tenants,
		"Filter":             filter,
		"FilterPaid":         paidFilterValue(c),
		"FilterExcluded":     excludedFilterValue(c.Query("excluded")),
		"PaymentTypes":       paymentTypeOptions(),
		"ViewMode":           viewMode,
		"ListViewURL":        paymentListURL(c, map[string]string{"view": adminPaymentViewList}),
		"GridViewURL":        paymentListURL(c, map[string]string{"view": adminPaymentViewGrid}),
		"CardViewURL":        paymentListURL(c, map[string]string{"view": adminPaymentViewCard}),
		"ClearFilterURL":     paymentClearURL(viewMode),
		"SummaryScopes":      paymentSummaryScopes(c),
		"SelectedSort":       paymentSortValue(filter),
		"PaidChips":          paymentPaidChips(c),
		"PeriodChips":        paymentPeriodChips(c),
		"TypeChips":          paymentTypeChips(c),
		"ExcludedChips":      paymentExcludedChips(c),
		"TenantStatusChips":  paymentTenantStatusChips(c),
		"SortHeaders":        paymentSortHeaders(c, filter),
		"Page":               page,
		"HasMore":            hasMore,
		"NextPageURL":        nextPageURL,
		"Total":              result.Total,
		"Error":              queryError(c),
	}, nil
}

func isHTMXRequest(c *gin.Context) bool {
	return c.GetHeader("HX-Request") == "true"
}

// hydrateQueryFromHXCurrentURL copies the query string from the HTMX
// HX-Current-URL header onto the inbound request, so that subsequent
// c.Query(...) calls reflect the filter context the user is currently viewing.
// Without this, POST actions like /payments/:id/toggle would lose the active
// filters and the rebuilt partial would snap back to the default view.
func hydrateQueryFromHXCurrentURL(c *gin.Context) {
	raw := c.GetHeader("HX-Current-URL")
	if raw == "" {
		return
	}
	parsed, err := url.Parse(raw)
	if err != nil {
		return
	}
	c.Request.URL.RawQuery = parsed.RawQuery
}

var (
	errPaymentGenerate = paymentError("生成应收记录失败")
	errPaymentList     = paymentError("读取收款记录失败")
	errPaymentSummary  = paymentError("读取收款汇总失败")
	errPaymentTenants  = paymentError("读取租客失败")
)

type paymentError string

func (e paymentError) Error() string { return string(e) }

func paymentToRow(payment model.Payment, now time.Time) paymentRow {
	today := paymentAPIDateOnly(now)
	payDate := paymentAPIDateOnly(payment.PayDate)
	overdue := !payment.Paid && !payment.Excluded && !payDate.IsZero() && payDate.Before(today)
	overdueDays := 0
	if overdue {
		overdueDays = int(today.Sub(payDate).Hours() / 24)
	}
	nextLabel := formatDisplayDate(payment.PayDate)
	if model.RentTypeOrDefault(payment.Tenant.RentType) == model.RentTypeDaily {
		nextLabel = "每日"
	}
	return paymentRow{
		ID:                payment.ID,
		TenantID:          payment.TenantID,
		TenantName:        payment.Tenant.Name,
		RoomNo:            payment.Tenant.Room.RoomNo,
		RoomTitle:         payment.Tenant.Room.Title,
		TenantStatus:      payment.Tenant.Status,
		TenantStatusLabel: tenantStatusLabelDisplay(payment.Tenant.Status),
		Type:              payment.Type,
		TypeLabel:         paymentTypeLabelText(payment.Type),
		AmountFen:         payment.Amount,
		AmountText:        service.FormatFen(payment.Amount),
		PayDate:           payment.PayDate,
		PayDateLabel:      formatDisplayDate(payment.PayDate),
		NextDueLabel:      nextLabel,
		Paid:              payment.Paid,
		StatusLabel:       paymentStatusLabelText(payment.Paid),
		Excluded:          payment.Excluded,
		ExclusionNote:     payment.ExclusionNote,
		AutoGenerated:     payment.AutoGenerated,
		Overdue:           overdue,
		OverdueDays:       overdueDays,
		OverdueLabel:      overdueLabelText(overdueDays),
		Note:              payment.Note,
		RentTypeLabel:     rentTypeLabelText(payment.Tenant.RentType),
	}
}

func tenantStatusLabelDisplay(status string) string {
	switch status {
	case model.TenantStatusActive:
		return "在租"
	case model.TenantStatusCheckout:
		return "已退租"
	default:
		return "未知"
	}
}

func paymentChip(label string, c *gin.Context, key string, value string, active bool) filterChip {
	overrides := map[string]string{key: value, "page": ""}
	return filterChip{Label: label, URL: paymentListURL(c, overrides), Active: active}
}

type paymentSummaryScope struct {
	URL    string
	Active bool
}

func paymentSummaryScopes(c *gin.Context) map[string]paymentSummaryScope {
	paid := paidFilterValue(c)
	excluded := excludedFilterValue(c.Query("excluded"))
	tenantStatus := strings.TrimSpace(c.Query("tenant_status"))
	period := strings.TrimSpace(c.Query("period"))
	typeFilter := strings.TrimSpace(c.Query("type"))

	unpaidActive := paid == "false" && excluded == "false" && tenantStatus != model.TenantStatusCheckout
	paidActive := paid == "true" && excluded == "false"
	excludedActive := excluded == "true"
	checkoutActive := tenantStatus == model.TenantStatusCheckout && excluded == "false" && paid == "false"
	_ = period
	_ = typeFilter

	return map[string]paymentSummaryScope{
		"unpaid": {
			URL:    paymentListURL(c, map[string]string{"paid": "false", "excluded": "false", "tenant_status": "", "page": ""}),
			Active: unpaidActive,
		},
		"paid": {
			URL:    paymentListURL(c, map[string]string{"paid": "true", "excluded": "false", "tenant_status": "", "page": ""}),
			Active: paidActive,
		},
		"checkout": {
			URL:    paymentListURL(c, map[string]string{"paid": "false", "excluded": "false", "tenant_status": model.TenantStatusCheckout, "page": ""}),
			Active: checkoutActive,
		},
		"excluded": {
			URL:    paymentListURL(c, map[string]string{"paid": "all", "excluded": "true", "tenant_status": "", "page": ""}),
			Active: excludedActive,
		},
	}
}

func paymentPaidChips(c *gin.Context) []filterChip {
	current := paidFilterValue(c)
	return []filterChip{
		paymentChip("全部", c, "paid", "all", current == "all"),
		paymentChip("未付款", c, "paid", "false", current == "false"),
		paymentChip("已付款", c, "paid", "true", current == "true"),
	}
}

func paymentPeriodChips(c *gin.Context) []filterChip {
	current := c.Query("period")
	return []filterChip{
		paymentChip("全部月份", c, "period", "", current == ""),
		paymentChip("当日", c, "period", "today", current == "today"),
		paymentChip("当周", c, "period", "week", current == "week"),
		paymentChip("当月", c, "period", "month", current == "month"),
	}
}

func paymentTypeChips(c *gin.Context) []filterChip {
	current := c.Query("type")
	chips := []filterChip{paymentChip("全部类型", c, "type", "", current == "")}
	for _, opt := range paymentTypeOptions() {
		chips = append(chips, paymentChip(opt.Label, c, "type", opt.Value, current == opt.Value))
	}
	return chips
}

func tenantStatusFilterValue(value string) string {
	switch value {
	case model.TenantStatusActive, model.TenantStatusCheckout:
		return value
	default:
		return ""
	}
}

func paymentTenantStatusChips(c *gin.Context) []filterChip {
	current := tenantStatusFilterValue(c.Query("tenant_status"))
	return []filterChip{
		paymentChip("全部租客", c, "tenant_status", "", current == ""),
		paymentChip("在租", c, "tenant_status", model.TenantStatusActive, current == model.TenantStatusActive),
		paymentChip("已退租", c, "tenant_status", model.TenantStatusCheckout, current == model.TenantStatusCheckout),
	}
}

func paymentExcludedChips(c *gin.Context) []filterChip {
	current := excludedFilterValue(c.Query("excluded"))
	return []filterChip{
		paymentChip("全部", c, "excluded", "all", current == "all"),
		paymentChip("正常记录", c, "excluded", "false", current == "false"),
		paymentChip("已排除", c, "excluded", "true", current == "true"),
	}
}

func paymentSortHeaders(c *gin.Context, filter repository.PaymentFilter) []sortHeader {
	sortBy := filter.SortBy
	if sortBy == "" {
		sortBy = "next_pay_date"
	}
	sortDir := filter.SortDir
	if sortDir == "" {
		sortDir = "asc"
	}
	headers := []sortHeader{
		{Key: "tenant", Label: "租客"},
		{Key: "next_pay_date", Label: "租金月份"},
		{Key: "amount", Label: "金额"},
		{Key: "status", Label: "付款状态"},
	}
	for i, h := range headers {
		active := h.Key == sortBy
		nextDir := "asc"
		indicator := ""
		if active {
			if sortDir == "asc" {
				nextDir = "desc"
				indicator = "↑"
			} else {
				nextDir = "asc"
				indicator = "↓"
			}
		}
		overrides := map[string]string{"sort_by": h.Key, "sort_dir": nextDir, "page": ""}
		headers[i].URL = paymentListURL(c, overrides)
		headers[i].Active = active
		headers[i].Indicator = indicator
	}
	return headers
}

func (h *AdminPaymentHandler) APIList(c *gin.Context) {
	now := time.Now()
	if _, err := h.paymentService.GenerateDueRecordsForActiveTenants(now); err != nil {
		c.JSON(http.StatusInternalServerError, gin.H{"error": "生成应收记录失败"})
		return
	}
	filter := paymentFilterFromQuery(c)
	result, err := h.paymentService.ListPaymentsPage(filter, now)
	if err != nil {
		c.JSON(http.StatusInternalServerError, gin.H{"error": "读取收款记录失败"})
		return
	}
	summary, err := h.paymentService.SummarizePayments(filter, now)
	if err != nil {
		c.JSON(http.StatusInternalServerError, gin.H{"error": "读取收款汇总失败"})
		return
	}
	page := normalizePaymentPage(filter.Page)
	limit := normalizePaymentLimit(filter.Limit)
	items := make([]paymentAPIItem, len(result.Payments))
	for i, payment := range result.Payments {
		items[i] = paymentToAPIItem(payment, now)
	}
	c.JSON(http.StatusOK, paymentAPIResponse{
		Data:    items,
		Summary: paymentSummaryToAPI(summary),
		Page:    page,
		Limit:   limit,
		Total:   result.Total,
		HasMore: int64(page*limit) < result.Total,
	})
}

func (h *AdminPaymentHandler) Create(c *gin.Context) {
	input, err := paymentInputFromForm(c)
	if err != nil {
		h.respondAfterPaymentCreate(c, "表单数据不正确")
		return
	}
	if _, err := h.paymentService.RecordPayment(input); err != nil {
		h.respondAfterPaymentCreate(c, userFacingError(err))
		return
	}
	h.respondAfterPaymentCreate(c, "")
}

func (h *AdminPaymentHandler) respondAfterPaymentCreate(c *gin.Context, errMsg string) {
	if isHTMXRequest(c) {
		hydrateQueryFromHXCurrentURL(c)
		data, err := h.buildPaymentListData(c)
		if err != nil {
			c.String(http.StatusInternalServerError, err.Error())
			return
		}
		if errMsg != "" {
			data["Error"] = errMsg
		} else {
			c.Header("HX-Trigger", "payment-created")
		}
		h.renderer.RenderPartial(c, http.StatusOK, "admin/payments.html", "admin_payment_list", data)
		return
	}
	if errMsg != "" {
		redirectWithError(c, "/admin/payments", errMsg)
		return
	}
	c.Redirect(http.StatusSeeOther, "/admin/payments")
}

func (h *AdminPaymentHandler) Toggle(c *gin.Context) {
	id, ok := parseUintParam(c, "id")
	if !ok {
		return
	}
	if err := h.paymentService.TogglePaid(id); err != nil {
		h.respondAfterPaymentAction(c, userFacingError(err))
		return
	}
	h.respondAfterPaymentAction(c, "")
}

func (h *AdminPaymentHandler) UpdateExclusion(c *gin.Context) {
	id, ok := parseUintParam(c, "id")
	if !ok {
		return
	}
	excluded := c.PostForm("excluded") == "true"
	if err := h.paymentService.SetExcluded(id, excluded, c.PostForm("exclusion_note")); err != nil {
		h.respondAfterPaymentAction(c, userFacingError(err))
		return
	}
	h.respondAfterPaymentAction(c, "")
}

func (h *AdminPaymentHandler) respondAfterPaymentAction(c *gin.Context, errMsg string) {
	if isHTMXRequest(c) {
		hydrateQueryFromHXCurrentURL(c)
		data, err := h.buildPaymentListData(c)
		if err != nil {
			c.String(http.StatusInternalServerError, err.Error())
			return
		}
		if errMsg != "" {
			data["Error"] = errMsg
		}
		h.renderer.RenderPartial(c, http.StatusOK, "admin/payments.html", "admin_payment_list", data)
		return
	}
	target := paymentRedirectTarget(c)
	if errMsg != "" {
		redirectWithError(c, target, errMsg)
		return
	}
	c.Redirect(http.StatusSeeOther, target)
}

func (h *AdminPaymentHandler) Exclude(c *gin.Context) {
	id, ok := parseUintParam(c, "id")
	if !ok {
		return
	}
	var input paymentExclusionRequest
	if err := c.ShouldBindJSON(&input); err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"error": "请求数据不正确"})
		return
	}
	note := input.ExclusionNote
	if strings.TrimSpace(note) == "" {
		note = input.Note
	}
	if err := h.paymentService.SetExcluded(id, input.Excluded, note); err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"error": userFacingError(err)})
		return
	}
	c.JSON(http.StatusOK, gin.H{"success": true})
}

func paymentFilterFromQuery(c *gin.Context) repository.PaymentFilter {
	filter := repository.PaymentFilter{
		Type:         c.Query("type"),
		Query:        c.Query("q"),
		Period:       c.Query("period"),
		TenantStatus: tenantStatusFilterValue(c.Query("tenant_status")),
		Page:         queryInt(c, "page"),
		Limit:        queryInt(c, "limit"),
		SortBy:       c.Query("sort_by"),
		SortDir:      c.Query("sort_dir"),
	}
	filter.Paid = paidQuery(c)
	filter.Excluded = excludedQuery(c.Query("excluded"))
	filter.Overdue = boolQuery(c.Query("overdue"))
	if tenantID, err := strconv.ParseUint(c.Query("tenant_id"), 10, 64); err == nil {
		filter.TenantID = uint(tenantID)
		// A direct tenant pick from the dropdown is authoritative; the human-
		// readable label still in `q` would otherwise LIKE-match nothing and
		// AND the result down to zero rows.
		if filter.TenantID > 0 {
			filter.Query = ""
		}
	}
	if fromDate, ok := dateQuery(c.Query("from")); ok {
		filter.FromDate = fromDate
	}
	if toDate, ok := dateQuery(c.Query("to")); ok {
		filter.ToDate = toDate
	}
	return filter
}

func paymentInputFromForm(c *gin.Context) (service.PaymentInput, error) {
	input := service.PaymentInput{
		AmountYuan: c.PostForm("amount"),
		Type:       c.PostForm("type"),
		Paid:       c.PostForm("paid") == "on",
		Note:       c.PostForm("note"),
	}
	tenantID, err := parseUintForm(c, "tenant_id")
	if err != nil {
		return input, err
	}
	input.TenantID = tenantID
	payDate, err := parseDateForm(c, "pay_date")
	if err != nil {
		return input, err
	}
	input.PayDate = payDate
	return input, nil
}

func paymentTypeOptions() []SelectOption {
	return []SelectOption{
		{Value: model.PaymentTypeRent, Label: "租金"},
		{Value: model.PaymentTypeWater, Label: "水费"},
		{Value: model.PaymentTypeElectricity, Label: "电费"},
		{Value: model.PaymentTypeOther, Label: "其他"},
	}
}

func paymentSummaryToAPI(summary repository.PaymentSummary) paymentAPISummary {
	return paymentAPISummary{
		TotalUnpaidAmountFen:  summary.TotalUnpaidAmount,
		TotalUnpaidAmountText: service.FormatFen(summary.TotalUnpaidAmount),
		TotalPaidAmountFen:    summary.TotalPaidAmount,
		TotalPaidAmountText:   service.FormatFen(summary.TotalPaidAmount),
		CheckoutPendingCount:  summary.CheckoutPendingCount,
		ExcludedCount:         summary.ExcludedCount,
	}
}

func paymentToAPIItem(payment model.Payment, now time.Time) paymentAPIItem {
	today := paymentAPIDateOnly(now)
	payDate := paymentAPIDateOnly(payment.PayDate)
	paymentStatus := "unpaid"
	if payment.Paid {
		paymentStatus = "paid"
	}
	overdue := !payment.Paid && !payment.Excluded && !payDate.IsZero() && payDate.Before(today)
	overdueDays := 0
	if overdue {
		overdueDays = int(today.Sub(payDate).Hours() / 24)
	}
	nextPayDateLabel := formatAPIDate(payment.PayDate)
	if model.RentTypeOrDefault(payment.Tenant.RentType) == model.RentTypeDaily {
		nextPayDateLabel = "每日"
	}
	return paymentAPIItem{
		ID:                payment.ID,
		PaymentID:         payment.ID,
		TenantID:          payment.TenantID,
		TenantName:        payment.Tenant.Name,
		RoomNo:            payment.Tenant.Room.RoomNo,
		Room:              payment.Tenant.Room.RoomNo,
		TenantStatus:      payment.Tenant.Status,
		Phone:             payment.Tenant.Phone,
		RentPriceFen:      payment.Tenant.RentPrice,
		RentPriceText:     service.FormatFenAsYuanInt(payment.Tenant.RentPrice),
		RentType:          payment.Tenant.RentType,
		RentTypeLabel:     rentTypeLabelText(payment.Tenant.RentType),
		PaymentTerms:      payment.Tenant.PaymentTerms,
		PaymentTermsLabel: paymentTermsLabelText(payment.Tenant.PaymentTerms),
		CheckinDate:       formatAPIDate(payment.Tenant.CheckinDate),
		LeaseEndDate:      formatOptionalAPIDate(payment.Tenant.LeaseEndDate),
		PayDate:           formatAPIDate(payment.PayDate),
		NextPayDateLabel:  nextPayDateLabel,
		Type:              payment.Type,
		TypeLabel:         paymentTypeLabelText(payment.Type),
		AmountFen:         payment.Amount,
		AmountText:        service.FormatFen(payment.Amount),
		Paid:              payment.Paid,
		PaymentStatus:     paymentStatus,
		StatusLabel:       paymentStatusLabelText(payment.Paid),
		Excluded:          payment.Excluded,
		ExclusionNote:     payment.ExclusionNote,
		AutoGenerated:     payment.AutoGenerated,
		Overdue:           overdue,
		OverdueDays:       overdueDays,
		OverdueLabel:      overdueLabelText(overdueDays),
		Note:              payment.Note,
	}
}

func queryInt(c *gin.Context, name string) int {
	value := strings.TrimSpace(c.Query(name))
	if value == "" {
		return 0
	}
	parsed, err := strconv.Atoi(value)
	if err != nil {
		return 0
	}
	return parsed
}

func boolQuery(value string) *bool {
	switch value {
	case "true":
		parsed := true
		return &parsed
	case "false":
		parsed := false
		return &parsed
	default:
		return nil
	}
}

func paidQuery(c *gin.Context) *bool {
	value, exists := c.GetQuery("paid")
	if !exists {
		parsed := false
		return &parsed
	}
	return boolQuery(value)
}

func paidFilterValue(c *gin.Context) string {
	value, exists := c.GetQuery("paid")
	if !exists {
		return "false"
	}
	switch value {
	case "all", "true":
		return value
	default:
		return "false"
	}
}

func excludedQuery(value string) *bool {
	switch value {
	case "all":
		return nil
	case "true":
		parsed := true
		return &parsed
	default:
		parsed := false
		return &parsed
	}
}

func excludedFilterValue(value string) string {
	switch value {
	case "all", "true":
		return value
	default:
		return "false"
	}
}

func dateQuery(value string) (time.Time, bool) {
	value = strings.TrimSpace(value)
	if value == "" {
		return time.Time{}, false
	}
	parsed, err := time.ParseInLocation("2006-01-02", value, time.Local)
	if err != nil {
		return time.Time{}, false
	}
	return parsed, true
}

func normalizePaymentPage(page int) int {
	if page < 1 {
		return 1
	}
	return page
}

func normalizePaymentLimit(limit int) int {
	if limit <= 0 {
		return 20
	}
	if limit > 100 {
		return 100
	}
	return limit
}

func paymentAPIDateOnly(value time.Time) time.Time {
	if value.IsZero() {
		return time.Time{}
	}
	return time.Date(value.Year(), value.Month(), value.Day(), 0, 0, 0, 0, value.Location())
}

// formatAPIDate emits ISO yyyy-MM-dd for JSON API consumers. JavaScript on the
// frontend reformats it into the Chinese display style via formatDisplayDate.
func formatAPIDate(value time.Time) string {
	if value.IsZero() {
		return ""
	}
	return value.Format("2006-01-02")
}

func formatOptionalAPIDate(value *time.Time) string {
	if value == nil || value.IsZero() {
		return ""
	}
	return value.Format("2006-01-02")
}

// formatDisplayDate renders a Chinese-style date used for server-rendered
// labels (e.g., "2026年5月23日"). Returns empty string for zero values.
func formatDisplayDate(value time.Time) string {
	if value.IsZero() {
		return ""
	}
	return fmt.Sprintf("%d年%d月%d日", value.Year(), int(value.Month()), value.Day())
}

func overdueLabelText(days int) string {
	if days <= 0 {
		return ""
	}
	return "逾期 " + strconv.Itoa(days) + " 天"
}

func paymentStatusLabelText(paid bool) string {
	if paid {
		return "已付款"
	}
	return "未付款"
}

func paymentTypeLabelText(paymentType string) string {
	switch paymentType {
	case model.PaymentTypeRent:
		return "租金"
	case model.PaymentTypeWater:
		return "水费"
	case model.PaymentTypeElectricity:
		return "电费"
	case model.PaymentTypeOther:
		return "其他"
	default:
		return "未知"
	}
}

func rentTypeLabelText(rentType string) string {
	if model.RentTypeOrDefault(rentType) == model.RentTypeDaily {
		return "日租"
	}
	return "月租"
}

func paymentTermsLabelText(paymentTerms string) string {
	switch model.PaymentTermsOrDefault(paymentTerms) {
	case model.PaymentTerms1M2D:
		return "付一押二"
	case model.PaymentTerms3M1D:
		return "付三押一"
	case model.PaymentTerms6M0D:
		return "半年付"
	case model.PaymentTerms12M0D:
		return "年付"
	default:
		return "付一押一"
	}
}
