package handler

import (
	"net/http"
	"strconv"
	"strings"
	"time"

	"github.com/gin-gonic/gin"
	"github.com/troublesis/rent/internal/model"
	"github.com/troublesis/rent/internal/repository"
	"github.com/troublesis/rent/internal/service"
)

type AdminPaymentHandler struct {
	renderer       Renderer
	paymentService *service.PaymentService
	tenantService  *service.TenantService
}

type paymentAPIResponse struct {
	Data    []paymentAPIItem  `json:"data"`
	Summary paymentAPISummary `json:"summary"`
	Page    int               `json:"page"`
	Limit   int               `json:"limit"`
	Total   int64             `json:"total"`
	HasMore bool              `json:"has_more"`
}

type paymentAPISummary struct {
	TotalUnpaidAmountFen  int    `json:"total_unpaid_amount_fen"`
	TotalUnpaidAmountText string `json:"total_unpaid_amount_text"`
	TotalPaidAmountFen    int    `json:"total_paid_amount_fen"`
	TotalPaidAmountText   string `json:"total_paid_amount_text"`
	CheckoutPendingCount  int64  `json:"checkout_pending_count"`
	ExcludedCount         int64  `json:"excluded_count"`
}

type paymentExclusionRequest struct {
	Excluded      bool   `json:"excluded"`
	ExclusionNote string `json:"exclusion_note"`
	Note          string `json:"note"`
}

type paymentAPIItem struct {
	ID                uint   `json:"id"`
	PaymentID         uint   `json:"payment_id"`
	TenantID          uint   `json:"tenant_id"`
	TenantName        string `json:"tenant_name"`
	RoomNo            string `json:"room_no"`
	Room              string `json:"room"`
	TenantStatus      string `json:"tenant_status"`
	Phone             string `json:"phone"`
	RentPriceFen      int    `json:"rent_price_fen"`
	RentPriceText     string `json:"rent_price_text"`
	RentType          string `json:"rent_type"`
	RentTypeLabel     string `json:"rent_type_label"`
	PaymentTerms      string `json:"payment_terms"`
	PaymentTermsLabel string `json:"payment_terms_label"`
	CheckinDate       string `json:"checkin_date"`
	LeaseEndDate      string `json:"lease_end_date"`
	PayDate           string `json:"pay_date"`
	NextPayDateLabel  string `json:"next_pay_date_label"`
	Type              string `json:"type"`
	TypeLabel         string `json:"type_label"`
	AmountFen         int    `json:"amount_fen"`
	AmountText        string `json:"amount_text"`
	Paid              bool   `json:"paid"`
	PaymentStatus     string `json:"payment_status"`
	StatusLabel       string `json:"status_label"`
	Excluded          bool   `json:"excluded"`
	ExclusionNote     string `json:"exclusion_note"`
	AutoGenerated     bool   `json:"auto_generated"`
	Overdue           bool   `json:"overdue"`
	OverdueDays       int    `json:"overdue_days"`
	OverdueLabel      string `json:"overdue_label"`
	Note              string `json:"note"`
}

func NewAdminPaymentHandler(renderer Renderer, paymentService *service.PaymentService, tenantService *service.TenantService) *AdminPaymentHandler {
	return &AdminPaymentHandler{renderer: renderer, paymentService: paymentService, tenantService: tenantService}
}

func (h *AdminPaymentHandler) List(c *gin.Context) {
	now := time.Now()
	if _, err := h.paymentService.GenerateDueRecordsForActiveTenants(now); err != nil {
		c.String(http.StatusInternalServerError, "生成应收记录失败")
		return
	}
	filter := paymentFilterFromQuery(c)
	items, err := h.paymentService.ListPaymentItems(filter, now)
	if err != nil {
		c.String(http.StatusInternalServerError, "读取收款记录失败")
		return
	}
	tenants, err := h.tenantService.ListTenants(repository.TenantFilter{Status: model.TenantStatusActive})
	if err != nil {
		c.String(http.StatusInternalServerError, "读取租客失败")
		return
	}
	h.renderer.Render(c, http.StatusOK, "admin_base.html", "admin/payments.html", gin.H{
		"Title":          "收款记录",
		"Items":          items,
		"Tenants":        tenants,
		"Filter":         filter,
		"FilterPaid":     c.Query("paid"),
		"FilterExcluded": excludedFilterValue(c.Query("excluded")),
		"PaymentTypes":   paymentTypeOptions(),
		"Error":          queryError(c),
	})
}

func (h *AdminPaymentHandler) APIList(c *gin.Context) {
	now := time.Now()
	if _, err := h.paymentService.GenerateDueRecordsForActiveTenants(now); err != nil {
		c.JSON(http.StatusInternalServerError, gin.H{"error": "生成应收记录失败"})
		return
	}
	filter := paymentFilterFromQuery(c)
	result, err := h.paymentService.ListPaymentsPage(filter, now)
	if err != nil {
		c.JSON(http.StatusInternalServerError, gin.H{"error": "读取收款记录失败"})
		return
	}
	summary, err := h.paymentService.SummarizePayments(filter, now)
	if err != nil {
		c.JSON(http.StatusInternalServerError, gin.H{"error": "读取收款汇总失败"})
		return
	}
	page := normalizePaymentPage(filter.Page)
	limit := normalizePaymentLimit(filter.Limit)
	items := make([]paymentAPIItem, len(result.Payments))
	for i, payment := range result.Payments {
		items[i] = paymentToAPIItem(payment, now)
	}
	c.JSON(http.StatusOK, paymentAPIResponse{
		Data:    items,
		Summary: paymentSummaryToAPI(summary),
		Page:    page,
		Limit:   limit,
		Total:   result.Total,
		HasMore: int64(page*limit) < result.Total,
	})
}

func (h *AdminPaymentHandler) Create(c *gin.Context) {
	input, err := paymentInputFromForm(c)
	if err != nil {
		redirectWithError(c, "/admin/payments", "表单数据不正确")
		return
	}
	if _, err := h.paymentService.RecordPayment(input); err != nil {
		redirectWithError(c, "/admin/payments", userFacingError(err))
		return
	}
	c.Redirect(http.StatusSeeOther, "/admin/payments")
}

func (h *AdminPaymentHandler) Toggle(c *gin.Context) {
	id, ok := parseUintParam(c, "id")
	if !ok {
		return
	}
	if err := h.paymentService.TogglePaid(id); err != nil {
		redirectWithError(c, "/admin/payments", userFacingError(err))
		return
	}
	c.Redirect(http.StatusSeeOther, "/admin/payments")
}

func (h *AdminPaymentHandler) UpdateExclusion(c *gin.Context) {
	id, ok := parseUintParam(c, "id")
	if !ok {
		return
	}
	excluded := c.PostForm("excluded") == "true"
	if err := h.paymentService.SetExcluded(id, excluded, c.PostForm("exclusion_note")); err != nil {
		redirectWithError(c, "/admin/payments", userFacingError(err))
		return
	}
	c.Redirect(http.StatusSeeOther, "/admin/payments")
}

func (h *AdminPaymentHandler) Exclude(c *gin.Context) {
	id, ok := parseUintParam(c, "id")
	if !ok {
		return
	}
	var input paymentExclusionRequest
	if err := c.ShouldBindJSON(&input); err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"error": "请求数据不正确"})
		return
	}
	note := input.ExclusionNote
	if strings.TrimSpace(note) == "" {
		note = input.Note
	}
	if err := h.paymentService.SetExcluded(id, input.Excluded, note); err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"error": userFacingError(err)})
		return
	}
	c.JSON(http.StatusOK, gin.H{"success": true})
}

func paymentFilterFromQuery(c *gin.Context) repository.PaymentFilter {
	filter := repository.PaymentFilter{
		Type:    c.Query("type"),
		Query:   c.Query("q"),
		Period:  c.Query("period"),
		Page:    queryInt(c, "page"),
		Limit:   queryInt(c, "limit"),
		SortBy:  c.Query("sort_by"),
		SortDir: c.Query("sort_dir"),
	}
	filter.Paid = boolQuery(c.Query("paid"))
	filter.Excluded = excludedQuery(c.Query("excluded"))
	filter.Overdue = boolQuery(c.Query("overdue"))
	if tenantID, err := strconv.ParseUint(c.Query("tenant_id"), 10, 64); err == nil {
		filter.TenantID = uint(tenantID)
	}
	if fromDate, ok := dateQuery(c.Query("from")); ok {
		filter.FromDate = fromDate
	}
	if toDate, ok := dateQuery(c.Query("to")); ok {
		filter.ToDate = toDate
	}
	return filter
}

func paymentInputFromForm(c *gin.Context) (service.PaymentInput, error) {
	input := service.PaymentInput{
		AmountYuan: c.PostForm("amount"),
		Type:       c.PostForm("type"),
		Paid:       c.PostForm("paid") == "on",
		Note:       c.PostForm("note"),
	}
	tenantID, err := parseUintForm(c, "tenant_id")
	if err != nil {
		return input, err
	}
	input.TenantID = tenantID
	payDate, err := parseDateForm(c, "pay_date")
	if err != nil {
		return input, err
	}
	input.PayDate = payDate
	return input, nil
}

func paymentTypeOptions() []SelectOption {
	return []SelectOption{
		{Value: model.PaymentTypeRent, Label: "租金"},
		{Value: model.PaymentTypeWater, Label: "水费"},
		{Value: model.PaymentTypeElectricity, Label: "电费"},
		{Value: model.PaymentTypeOther, Label: "其他"},
	}
}

func paymentSummaryToAPI(summary repository.PaymentSummary) paymentAPISummary {
	return paymentAPISummary{
		TotalUnpaidAmountFen:  summary.TotalUnpaidAmount,
		TotalUnpaidAmountText: service.FormatFen(summary.TotalUnpaidAmount),
		TotalPaidAmountFen:    summary.TotalPaidAmount,
		TotalPaidAmountText:   service.FormatFen(summary.TotalPaidAmount),
		CheckoutPendingCount:  summary.CheckoutPendingCount,
		ExcludedCount:         summary.ExcludedCount,
	}
}

func paymentToAPIItem(payment model.Payment, now time.Time) paymentAPIItem {
	today := paymentAPIDateOnly(now)
	payDate := paymentAPIDateOnly(payment.PayDate)
	paymentStatus := "unpaid"
	if payment.Paid {
		paymentStatus = "paid"
	}
	overdue := !payment.Paid && !payment.Excluded && !payDate.IsZero() && payDate.Before(today)
	overdueDays := 0
	if overdue {
		overdueDays = int(today.Sub(payDate).Hours() / 24)
	}
	nextPayDateLabel := formatAPIDate(payment.PayDate)
	if model.RentTypeOrDefault(payment.Tenant.RentType) == model.RentTypeDaily {
		nextPayDateLabel = "每日"
	}
	return paymentAPIItem{
		ID:                payment.ID,
		PaymentID:         payment.ID,
		TenantID:          payment.TenantID,
		TenantName:        payment.Tenant.Name,
		RoomNo:            payment.Tenant.Room.RoomNo,
		Room:              payment.Tenant.Room.RoomNo,
		TenantStatus:      payment.Tenant.Status,
		Phone:             payment.Tenant.Phone,
		RentPriceFen:      payment.Tenant.RentPrice,
		RentPriceText:     service.FormatFen(payment.Tenant.RentPrice),
		RentType:          payment.Tenant.RentType,
		RentTypeLabel:     rentTypeLabelText(payment.Tenant.RentType),
		PaymentTerms:      payment.Tenant.PaymentTerms,
		PaymentTermsLabel: paymentTermsLabelText(payment.Tenant.PaymentTerms),
		CheckinDate:       formatAPIDate(payment.Tenant.CheckinDate),
		LeaseEndDate:      formatOptionalAPIDate(payment.Tenant.LeaseEndDate),
		PayDate:           formatAPIDate(payment.PayDate),
		NextPayDateLabel:  nextPayDateLabel,
		Type:              payment.Type,
		TypeLabel:         paymentTypeLabelText(payment.Type),
		AmountFen:         payment.Amount,
		AmountText:        service.FormatFen(payment.Amount),
		Paid:              payment.Paid,
		PaymentStatus:     paymentStatus,
		StatusLabel:       paymentStatusLabelText(payment.Paid),
		Excluded:          payment.Excluded,
		ExclusionNote:     payment.ExclusionNote,
		AutoGenerated:     payment.AutoGenerated,
		Overdue:           overdue,
		OverdueDays:       overdueDays,
		OverdueLabel:      overdueLabelText(overdueDays),
		Note:              payment.Note,
	}
}

func queryInt(c *gin.Context, name string) int {
	value := strings.TrimSpace(c.Query(name))
	if value == "" {
		return 0
	}
	parsed, err := strconv.Atoi(value)
	if err != nil {
		return 0
	}
	return parsed
}

func boolQuery(value string) *bool {
	switch value {
	case "true":
		parsed := true
		return &parsed
	case "false":
		parsed := false
		return &parsed
	default:
		return nil
	}
}

func excludedQuery(value string) *bool {
	switch value {
	case "all":
		return nil
	case "true":
		parsed := true
		return &parsed
	default:
		parsed := false
		return &parsed
	}
}

func excludedFilterValue(value string) string {
	switch value {
	case "all", "true":
		return value
	default:
		return "false"
	}
}

func dateQuery(value string) (time.Time, bool) {
	value = strings.TrimSpace(value)
	if value == "" {
		return time.Time{}, false
	}
	parsed, err := time.ParseInLocation("2006-01-02", value, time.Local)
	if err != nil {
		return time.Time{}, false
	}
	return parsed, true
}

func normalizePaymentPage(page int) int {
	if page < 1 {
		return 1
	}
	return page
}

func normalizePaymentLimit(limit int) int {
	if limit <= 0 {
		return 20
	}
	if limit > 100 {
		return 100
	}
	return limit
}

func paymentAPIDateOnly(value time.Time) time.Time {
	if value.IsZero() {
		return time.Time{}
	}
	return time.Date(value.Year(), value.Month(), value.Day(), 0, 0, 0, 0, value.Location())
}

func formatAPIDate(value time.Time) string {
	if value.IsZero() {
		return ""
	}
	return value.Format("2006-01-02")
}

func formatOptionalAPIDate(value *time.Time) string {
	if value == nil || value.IsZero() {
		return ""
	}
	return value.Format("2006-01-02")
}

func overdueLabelText(days int) string {
	if days <= 0 {
		return ""
	}
	return "逾期 " + strconv.Itoa(days) + " 天"
}

func paymentStatusLabelText(paid bool) string {
	if paid {
		return "已付款"
	}
	return "未付款"
}

func paymentTypeLabelText(paymentType string) string {
	switch paymentType {
	case model.PaymentTypeRent:
		return "租金"
	case model.PaymentTypeWater:
		return "水费"
	case model.PaymentTypeElectricity:
		return "电费"
	case model.PaymentTypeOther:
		return "其他"
	default:
		return "未知"
	}
}

func rentTypeLabelText(rentType string) string {
	if model.RentTypeOrDefault(rentType) == model.RentTypeDaily {
		return "日租"
	}
	return "月租"
}

func paymentTermsLabelText(paymentTerms string) string {
	switch model.PaymentTermsOrDefault(paymentTerms) {
	case model.PaymentTerms1M2D:
		return "付一押二"
	case model.PaymentTerms3M1D:
		return "付三押一"
	case model.PaymentTerms6M0D:
		return "半年付"
	case model.PaymentTerms12M0D:
		return "年付"
	default:
		return "付一押一"
	}
}
