package model

import "time"

const (
	RoomStatusVacant      = "vacant"
	RoomStatusOccupied    = "occupied"
	RoomStatusMaintenance = "maintenance"
)

const (
	TenantStatusActive   = "active"
	TenantStatusCheckout = "checkout"
)

const (
	TenantGenderMale   = "male"
	TenantGenderFemale = "female"
)

const (
	PaymentTypeRent        = "rent"
	PaymentTypeWater       = "water"
	PaymentTypeElectricity = "electricity"
	PaymentTypeOther       = "other"
)

const (
	MediaTypeImage     = "image"
	MediaTypeVideo     = "video"
	MediaTypeVideoLink = "video_link"
)

const (
	RentTypeMonthly = "monthly"
	RentTypeDaily   = "daily"
)

const (
	PaymentTerms1M1D  = "1m_1d"
	PaymentTerms1M2D  = "1m_2d"
	PaymentTerms3M1D  = "3m_1d"
	PaymentTerms6M0D  = "6m_0d"
	PaymentTerms12M0D = "12m_0d"
)

type Room struct {
	ID           uint   `gorm:"primarykey"`
	RoomNo       string `gorm:"uniqueIndex;not null"`
	Title        string `gorm:"not null"`
	Description  string
	Price        int
	RentType     string `gorm:"default:monthly;index"`
	RentPrice    int
	PaymentTerms string `gorm:"default:1m_1d"`
	Deposit      int
	Status       string `gorm:"default:vacant;index"`
	Area         int
	Floor        int
	Address      string
	Bedrooms     int
	LivingRooms  int
	Bathrooms    int
	Orientation  string
	Tags         string
	Media        []RoomMedia `gorm:"constraint:OnDelete:CASCADE"`
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

type RoomMedia struct {
	ID        uint   `gorm:"primarykey"`
	RoomID    uint   `gorm:"not null;index"`
	URL       string `gorm:"not null"`
	MediaType string `gorm:"not null;index"`
	CreatedAt time.Time
}

type Tenant struct {
	ID               uint   `gorm:"primarykey"`
	Name             string `gorm:"not null"`
	Phone            string `gorm:"not null"`
	EmergencyContact string
	Gender           string `gorm:"index"`
	RoomID           uint   `gorm:"not null;index"`
	Room             Room
	CheckinDate      time.Time
	LeaseEndDate     *time.Time `gorm:"index"`
	CheckoutDate     *time.Time
	RentPrice        int
	RentType         string `gorm:"default:monthly;index"`
	PaymentTerms     string `gorm:"default:1m_1d"`
	Deposit          int
	Notes            string `gorm:"type:text"`
	Status           string `gorm:"default:active;index"`
	Payments         []Payment
	CreatedAt        time.Time
	UpdatedAt        time.Time
}

type Payment struct {
	ID            uint `gorm:"primarykey"`
	TenantID      uint `gorm:"not null;index"`
	Tenant        Tenant
	Amount        int
	Type          string `gorm:"not null;index"`
	Paid          bool   `gorm:"default:false;index"`
	PayDate       time.Time
	Note          string
	AutoGenerated bool `gorm:"default:false;index"`
	Excluded      bool `gorm:"default:false;index"`
	ExclusionNote string
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

type AppSetting struct {
	ID        uint   `gorm:"primarykey"`
	Key       string `gorm:"uniqueIndex;not null"`
	Value     string
	CreatedAt time.Time
	UpdatedAt time.Time
}

func ValidRoomStatus(status string) bool {
	switch status {
	case RoomStatusVacant, RoomStatusOccupied, RoomStatusMaintenance:
		return true
	default:
		return false
	}
}

func ValidTenantStatus(status string) bool {
	switch status {
	case TenantStatusActive, TenantStatusCheckout:
		return true
	default:
		return false
	}
}

func ValidTenantGender(gender string) bool {
	switch gender {
	case "", TenantGenderMale, TenantGenderFemale:
		return true
	default:
		return false
	}
}

func ValidPaymentType(paymentType string) bool {
	switch paymentType {
	case PaymentTypeRent, PaymentTypeWater, PaymentTypeElectricity, PaymentTypeOther:
		return true
	default:
		return false
	}
}

func ValidMediaType(mediaType string) bool {
	switch mediaType {
	case MediaTypeImage, MediaTypeVideo, MediaTypeVideoLink:
		return true
	default:
		return false
	}
}

func ValidRentType(rentType string) bool {
	switch rentType {
	case RentTypeMonthly, RentTypeDaily:
		return true
	default:
		return false
	}
}

func ValidPaymentTerms(paymentTerms string) bool {
	switch paymentTerms {
	case PaymentTerms1M1D, PaymentTerms1M2D, PaymentTerms3M1D, PaymentTerms6M0D, PaymentTerms12M0D:
		return true
	default:
		return false
	}
}

func RentTypeOrDefault(rentType string) string {
	if ValidRentType(rentType) {
		return rentType
	}
	return RentTypeMonthly
}

func PaymentTermsOrDefault(paymentTerms string) string {
	if ValidPaymentTerms(paymentTerms) {
		return paymentTerms
	}
	return PaymentTerms1M1D
}

func PaymentTermsMonths(paymentTerms string) int {
	switch paymentTerms {
	case PaymentTerms3M1D:
		return 3
	case PaymentTerms6M0D:
		return 6
	case PaymentTerms12M0D:
		return 12
	default:
		return 1
	}
}

func RoomRentPrice(room Room) int {
	if room.RentPrice > 0 {
		return room.RentPrice
	}
	return room.Price
}
