package service

import (
	"fmt"
	"time"

	"github.com/troublesis/rent/internal/model"
	"github.com/troublesis/rent/internal/repository"
)

type PaymentInput struct {
	TenantID   uint
	AmountYuan string
	Type       string
	Paid       bool
	PayDate    time.Time
	Note       string
}

type PaymentListItem struct {
	Payment        model.Payment
	NextDueDate    time.Time
	NextDueLabel   string
	NextDueOverdue bool
}

type RentDue struct {
	TenantID uint
	DueDate  time.Time
	Amount   int
}

type PaymentService struct {
	paymentRepo *repository.PaymentRepository
	tenantRepo  *repository.TenantRepository
}

func NewPaymentService(paymentRepo *repository.PaymentRepository, tenantRepo *repository.TenantRepository) *PaymentService {
	return &PaymentService{paymentRepo: paymentRepo, tenantRepo: tenantRepo}
}

func (s *PaymentService) ListPayments(filter repository.PaymentFilter) ([]model.Payment, error) {
	return s.paymentRepo.ListPayments(filter)
}

func (s *PaymentService) ListPaymentItems(filter repository.PaymentFilter, now time.Time) ([]PaymentListItem, error) {
	payments, err := s.paymentRepo.ListPayments(filter)
	if err != nil {
		return nil, err
	}
	items := make([]PaymentListItem, len(payments))
	for i, payment := range payments {
		nextDueDate, nextDueLabel, overdue := NextDueForTenant(payment.Tenant, now)
		items[i] = PaymentListItem{Payment: payment, NextDueDate: nextDueDate, NextDueLabel: nextDueLabel, NextDueOverdue: overdue}
	}
	return items, nil
}

func (s *PaymentService) ListPaymentsPage(filter repository.PaymentFilter, now time.Time) (repository.PaymentListResult, error) {
	return s.paymentRepo.ListPaymentsPage(filter, now)
}

func (s *PaymentService) RecordPayment(input PaymentInput) (*model.Payment, error) {
	payment, err := buildPayment(input)
	if err != nil {
		return nil, err
	}
	if _, err := s.tenantRepo.GetTenant(input.TenantID); err != nil {
		return nil, err
	}
	if err := s.paymentRepo.CreatePayment(payment); err != nil {
		return nil, err
	}
	return payment, nil
}

func (s *PaymentService) GenerateDueRecords(tenantID uint, now time.Time) (int, error) {
	tenant, err := s.tenantRepo.GetTenant(tenantID)
	if err != nil {
		return 0, err
	}
	return s.generateDueRecordsForTenant(*tenant, now)
}

func (s *PaymentService) GenerateDueRecordsForActiveTenants(now time.Time) (int, error) {
	tenants, err := s.tenantRepo.ListActiveTenantsWithPayments()
	if err != nil {
		return 0, err
	}
	total := 0
	for _, tenant := range tenants {
		created, err := s.generateDueRecordsForTenant(tenant, now)
		if err != nil {
			return total, err
		}
		total += created
	}
	return total, nil
}

func (s *PaymentService) generateDueRecordsForTenant(tenant model.Tenant, now time.Time) (int, error) {
	dues := RentDueSchedule(tenant, now)
	payments := make([]model.Payment, 0, len(dues))
	for _, due := range dues {
		if hasRentRecordOnDate(tenant.Payments, due.DueDate) {
			continue
		}
		payments = append(payments, model.Payment{
			TenantID:      due.TenantID,
			Amount:        due.Amount,
			Type:          model.PaymentTypeRent,
			Paid:          false,
			PayDate:       due.DueDate,
			Note:          "系统自动生成租金应收",
			AutoGenerated: true,
		})
	}
	if err := s.paymentRepo.CreatePayments(payments); err != nil {
		return 0, err
	}
	return len(payments), nil
}

func (s *PaymentService) TogglePaid(id uint) error {
	payment, err := s.paymentRepo.GetPayment(id)
	if err != nil {
		return err
	}
	updatedPayment := *payment
	updatedPayment.Paid = !payment.Paid
	if updatedPayment.Paid {
		updatedPayment.Excluded = false
		updatedPayment.ExclusionNote = ""
	}
	return s.paymentRepo.UpdatePayment(&updatedPayment)
}

func (s *PaymentService) SetExcluded(id uint, excluded bool, note string) error {
	payment, err := s.paymentRepo.GetPayment(id)
	if err != nil {
		return err
	}
	if excluded && payment.Paid {
		return fmt.Errorf("已收款记录无需排除")
	}
	exclusionNote, err := validateNotes(note, "排除备注")
	if err != nil {
		return err
	}
	updatedPayment := *payment
	updatedPayment.Excluded = excluded
	if excluded {
		updatedPayment.ExclusionNote = exclusionNote
	} else {
		updatedPayment.ExclusionNote = ""
	}
	return s.paymentRepo.UpdatePayment(&updatedPayment)
}

func (s *PaymentService) SumPaidByMonth(year int, month time.Month) (int, error) {
	return s.paymentRepo.SumPaidByMonth(year, month)
}

func (s *PaymentService) SumUnpaid() (int, error) {
	return s.paymentRepo.SumUnpaid()
}

func (s *PaymentService) MonthlyIncome(year int) ([]repository.MonthlyIncomeRow, error) {
	return s.paymentRepo.MonthlyIncome(year)
}

func RentDueSchedule(tenant model.Tenant, through time.Time) []RentDue {
	if tenant.Status != "" && tenant.Status != model.TenantStatusActive {
		return []RentDue{}
	}
	if tenant.ID == 0 || tenant.RentPrice <= 0 || tenant.CheckinDate.IsZero() || through.IsZero() {
		return []RentDue{}
	}
	start := dateOnly(tenant.CheckinDate)
	end := dateOnly(through)
	if end.Before(start) {
		return []RentDue{}
	}
	if model.RentTypeOrDefault(tenant.RentType) == model.RentTypeDaily {
		return dailyRentDueSchedule(tenant, start, end)
	}
	return monthlyRentDueSchedule(tenant, start, end)
}

func dailyRentDueSchedule(tenant model.Tenant, start time.Time, end time.Time) []RentDue {
	dues := make([]RentDue, 0)
	for dueDate := start; !dueDate.After(end); dueDate = dueDate.AddDate(0, 0, 1) {
		dues = append(dues, RentDue{TenantID: tenant.ID, DueDate: dueDate, Amount: tenant.RentPrice})
	}
	return dues
}

func monthlyRentDueSchedule(tenant model.Tenant, start time.Time, end time.Time) []RentDue {
	cycleMonths := model.PaymentTermsMonths(tenant.PaymentTerms)
	amount := tenant.RentPrice * cycleMonths
	dues := make([]RentDue, 0)
	for dueDate := start; !dueDate.After(end); dueDate = dueDate.AddDate(0, cycleMonths, 0) {
		dues = append(dues, RentDue{TenantID: tenant.ID, DueDate: dueDate, Amount: amount})
	}
	return dues
}

func hasRentRecordOnDate(payments []model.Payment, dueDate time.Time) bool {
	for _, payment := range payments {
		if payment.Type != model.PaymentTypeRent {
			continue
		}
		if sameCalendarDate(payment.PayDate, dueDate) {
			return true
		}
	}
	return false
}

func sameCalendarDate(left time.Time, right time.Time) bool {
	leftDate := dateOnly(left)
	rightDate := dateOnly(right)
	return leftDate.Equal(rightDate)
}

func NextDueForTenant(tenant model.Tenant, now time.Time) (time.Time, string, bool) {
	if model.RentTypeOrDefault(tenant.RentType) == model.RentTypeDaily {
		return time.Time{}, "每日", true
	}
	lastPaidDate, hasPaidRent := latestPaidRentDate(tenant.Payments)
	if !hasPaidRent {
		dueDate := tenant.CheckinDate
		return dueDate, formatDueLabel(dueDate), dueDateBeforeToday(dueDate, now)
	}
	dueDate := lastPaidDate.AddDate(0, model.PaymentTermsMonths(tenant.PaymentTerms), 0)
	return dueDate, formatDueLabel(dueDate), dueDateBeforeToday(dueDate, now)
}

func buildPayment(input PaymentInput) (*model.Payment, error) {
	if input.TenantID == 0 {
		return nil, fmt.Errorf("请选择租客")
	}
	amount, err := ParseYuanToFen(input.AmountYuan)
	if err != nil {
		return nil, fmt.Errorf("收款金额不正确：%w", err)
	}
	if amount <= 0 {
		return nil, fmt.Errorf("收款金额需大于 0")
	}
	if !model.ValidPaymentType(input.Type) {
		return nil, fmt.Errorf("收款类型不正确")
	}
	note, err := validateNotes(input.Note, "备注")
	if err != nil {
		return nil, err
	}
	payDate := input.PayDate
	if payDate.IsZero() {
		payDate = time.Now()
	}
	return &model.Payment{
		TenantID: input.TenantID,
		Amount:   amount,
		Type:     input.Type,
		Paid:     input.Paid,
		PayDate:  payDate,
		Note:     note,
	}, nil
}

func latestPaidRentDate(payments []model.Payment) (time.Time, bool) {
	var latest time.Time
	found := false
	for _, payment := range payments {
		if payment.Type != model.PaymentTypeRent || !payment.Paid || payment.Excluded {
			continue
		}
		if !found || payment.PayDate.After(latest) {
			latest = payment.PayDate
			found = true
		}
	}
	return latest, found
}

func formatDueLabel(value time.Time) string {
	if value.IsZero() {
		return "-"
	}
	return value.Format("2006-01-02")
}

func dueDateBeforeToday(value time.Time, now time.Time) bool {
	if value.IsZero() {
		return false
	}
	today := time.Date(now.Year(), now.Month(), now.Day(), 0, 0, 0, 0, now.Location())
	dueDate := time.Date(value.Year(), value.Month(), value.Day(), 0, 0, 0, 0, now.Location())
	return dueDate.Before(today)
}
